const records = [
  ["Yoshua Bengio — official profile", "Yoshua Bengio", "https://yoshuabengio.org/en", "Current roles checked September 22, 2026."],
  ["Yoshua Bengio", "Mila", "https://mila.quebec/en/directory/yoshua-bengio", "Current appointment, scientific-advisor role, publications, and authentic professional-profile links."],
  ["ACM ByteCast — Yoshua Bengio transcript", "ACM / Rashmi Mohan", "https://learning.acm.org/binaries/content/assets/leaning-center/bytecast-transcripts/acm_bytecast_yoshua_bengio_corrected---transcript-updsated.pdf", "2024 first-person interview; retrieved during preliminary reporting, but publication-day retrieval was restricted."],
  ["Yoshua Bengio: He helped create AI. Now, he fears killer robots", "Dan Bilefsky / New York Times News Service, via Gulf News", "https://gulfnews.com/technology/trends/yoshua-bengio-he-helped-create-ai-now-he-fears-killer-robots-1.63019177", "April 10, 2019 interview-based profile. Historical roles are not current appointments."],
  ["Reflections by Yoshua Bengio", "Canada School of Public Service", "https://www.csps-efpc.gc.ca/video/yoshua-bengio-eng.aspx", "Public interview posted October 9, 2025; recollections attributed to the speaker."],
  ["Bengio co-recipient of A.M. Turing Award", "McGill University", "https://www.mcgill.ca/newsroom/channels/news/bengio-co-recipient-am-turing-award-295735", "2019 announcement; degree dates and shared 2018 award."],
  ["Yoshua Bengio — Prix Marie-Victorin", "Prix du Québec", "https://prixduquebec.gouv.qc.ca/recipiendaires/yoshua-bengio/", "2017 institutional biography, used for historical chronology only."],
  ["Artificial neural networks and their application to sequence recognition", "McGill eScholarship", "https://escholarship.mcgill.ca/concern/theses/qv33rx48q", "1991 doctoral thesis record."],
  ["Learning long-term dependencies with gradient descent is difficult", "IEEE Transactions on Neural Networks / PubMed", "https://pubmed.ncbi.nlm.nih.gov/18267787/", "Bengio, Patrice Simard, and Paolo Frasconi, 1994."],
  ["A Neural Probabilistic Language Model", "Journal of Machine Learning Research", "https://jmlr.org/papers/v3/bengio03a.html", "Bengio, Réjean Ducharme, Pascal Vincent, and Christian Jauvin, 2003."],
  ["Pan-Canadian AI Strategy annual report 2019", "CIFAR", "https://cifar.ca/wp-content/uploads/2020/04/ai_annualreport2019_web.pdf", "Historical account of the 2004 research program; not current staffing or impact statistics."],
  ["Exploring Strategies for Training Deep Neural Networks", "Journal of Machine Learning Research", "https://jmlr.org/papers/v10/larochelle09a.html", "Hugo Larochelle, Bengio, Jérôme Louradour, and Pascal Lamblin, 2009."],
  ["Neural Machine Translation by Jointly Learning to Align and Translate", "arXiv / ICLR", "https://arxiv.org/abs/1409.0473", "Dzmitry Bahdanau, Kyunghyun Cho, and Bengio; 2014 preprint, ICLR 2015."],
  ["Attention Is All You Need", "arXiv / NeurIPS", "https://arxiv.org/abs/1706.03762", "Vaswani and seven coauthors, 2017. Bengio is not an author of this Transformer paper."],
  ["Generative Adversarial Networks", "arXiv", "https://arxiv.org/abs/1406.2661", "Goodfellow and seven coauthors, including Bengio, 2014."],
  ["Theano: A Python framework for fast computation of mathematical expressions", "Theano Development Team / arXiv", "https://arxiv.org/abs/1605.02688", "2016 team paper; software contribution, not a claim of current maintenance."],
  ["Deep Learning", "Ian Goodfellow, Yoshua Bengio, Aaron Courville / MIT Press", "https://www.deeplearningbook.org/", "2016 textbook and authorized online reading edition."],
  ["Rise of the machines", "Daniel McCabe / McGill News", "https://mcgillnews.mcgill.ca/rise-of-the-machines/", "January 2018 reporting on Montreal's research community and Bengio's then-current views."],
  ["ServiceNow to Acquire AI Pioneer Element AI", "ServiceNow", "https://newsroom.servicenow.com/press-releases/details/2020/ServiceNow-to-Acquire-AI-Pioneer-Element-AI-11-30-2020-12-00-AM/default.aspx", "November 30, 2020 announcement, with January 8, 2021 completion update."],
  ["Element AI licencie 42 personnes", "Francis Halin / Le Journal de Montréal", "https://www.journaldemontreal.com/2020/12/02/element-ai-licencie-42-personnes", "December 2, 2020 reporting, ministry confirmation of a layoff notice, and company response."],
  ["The Montréal Declaration for a Responsible Development of Artificial Intelligence", "Montréal Declaration", "https://montrealdeclaration-responsibleai.com/the-declaration/", "Principles and collective drafting context; declaration is not enforceable law."],
  ["Presentation of the Montréal Declaration", "CIRANO", "https://cirano.qc.ca/en/news/794", "December 4, 2018 launch record."],
  ["Yoshua Bengio on honest AI — Radio Davos", "World Economic Forum", "https://www.weforum.org/podcasts/radio-davos/episodes/yoshua-bengio-honest-ai/", "2026 public interview with Robin Pomeroy. Machine-generated transcript used for broad attributed recollection, not verbatim quotation."],
  ["On the Dangers of Stochastic Parrots: Can Language Models Be Too Big?", "ACM FAccT", "https://doi.org/10.1145/3442188.3445922", "Bender, Gebru, McMillan-Major, and Shmitchell, 2021; primary critical perspective, not a response to LawZero's 2026 paper."],
  ["International AI Safety Report", "International AI Safety Report", "https://internationalaisafetyreport.org/", "2026 report released February 3; collective authorship and scope."],
  ["2026 Report: Executive Summary", "International AI Safety Report", "https://internationalaisafetyreport.org/publication/2026-report-executive-summary", "Dated evidence assessment, uncertainty, evaluation limitations, and categories of risk."],
  ["Introducing LawZero", "Yoshua Bengio", "https://yoshuabengio.org/en/blog/introducing-lawzero", "June 3, 2025 first-party launch announcement."],
  ["Team", "LawZero", "https://lawzero.org/en/team", "Leadership and board checked September 22, 2026."],
  ["LawZero advances safe-by-design AI with support from NVIDIA", "LawZero", "https://lawzero.org/en/news/lawzero-advances-safe-design-ai-support-nvidia", "July 2026 computing donation announcement; page header and body carry different July dates."],
  ["Safety from Honesty in a Disinterested AI Predictor", "arXiv", "https://arxiv.org/abs/2606.29657", "Bengio and 15 coauthors; June 28, 2026 preprint, revised July 10. Conditional formal argument, not deployed-system validation."],
  ["Why are AI agents lying, cheating and coordinating?", "Yoshua Bengio", "https://yoshuabengio.org/en/blog/why-are-ai-agents-lying-cheating-and-coordinating", "September 11, 2026 essay; hypotheses and projections attributed as such."],
  ["Canada and Germany invest in LawZero to build a new approach to safe, sovereign AI", "Government of Canada", "https://www.canada.ca/en/innovation-science-economic-development/news/2026/09/canada-and-germany-invest-in-lawzero-to-build-a-new-approach-to-safe-sovereign-ai.html", "September 16, 2026 planned investments; German funding subject to European Commission notification."],
  ["ICLR 2025 — Yoshua Bengio 03", "Xuthoria / Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:ICLR_2025_-_Yoshua_Bengio_03.jpg", "Own-work portrait, April 28, 2025, Singapore; CC BY-SA 4.0."],
  ["Research", "LawZero", "https://lawzero.org/en/research", "Current research program and publication listings checked September 22, 2026; aspirations distinguished from results."]
];
const sources = records.map(([title,publisher,url,note],i)=>({id:i+1,title,publisher,url,note}));
const ref = (...ids)=>ids.map(id=>`<sup class="source-ref"><a href="#source-${id}" aria-label="Source ${id}">${id}</a></sup>`).join("");
const sections = [
 ["brothers-and-machines","Two brothers and the machines they could program",`
 <p class="lead">Long before Yoshua Bengio was asked to explain artificial intelligence to governments, he and his brother were saving for computers. In a 2024 ACM interview, he recalled the Apple and Atari machines of their teenage years, teaching themselves to program, and writing games in BASIC. The attraction was not simply playing. It was discovering that they could make the machine do something of their own design.${ref(3)}</p>
 <p>The story is small enough to resist the mythology that now surrounds AI. There is no inevitable march from a home computer to a scientific prize. There are two young people, an unfamiliar instrument, and the pleasure of discovering its possibilities. The distance between giving a computer instructions and enabling it to learn would become the central territory of Bengio's working life.</p>
 <p>Today that territory contains a second question: what happens when a machine learns behavior its makers did not intend? Bengio remains a full professor at Université de Montréal, is Mila's founder and scientific advisor, and serves as co-president and scientific director of LawZero. His newest institution is pursuing AI safety. The change is not a departure from learning machines so much as a reconsideration of what their designers owe everyone else.${ref(1,2)}</p>`],
 ["origins","A childhood shaped by art and imagined futures",`
 <p>Bengio was born in France in 1964 and moved to Montreal at about twelve, as he recounted in a public-service interview. Migration connects the beginning of his biography to the city in which he would build his academic career; it does not, by itself, explain the choices he later made. His recollections offer a more particular account of what caught his attention.${ref(5)}</p>
 <p>In Dan Bilefsky's 2019 New York Times News Service profile, Bengio described parents from Casablanca who encouraged independent thought. His father combined pharmacy with directing theatre; his mother managed artists. Science fiction supplied another education. He read Asimov, Bradbury, and Clarke, and remembered being fascinated by the idea of teaching a machine in <em>2001: A Space Odyssey</em>. These are his reported formative influences, not evidence that a fictional future can be engineered into existence.${ref(4)}</p>
 <p>Art and computation need not be opposites in this account. One invites a person to imagine a world that does not yet exist; the other requires explicit steps that can be tested. RACH's reading of his subsequent career is that both impulses remained visible. He repeatedly chose ambitious questions, but his durable contributions came through particular models, mathematical difficulties, and collaborations—not through the ambition alone.</p>`],
 ["apprenticeship","Learning how to ask a research question",`
 <p>McGill records three degrees: an engineering bachelor's in 1986, a master's in 1988, and a doctorate in 1991. The doctoral thesis concerned artificial neural networks and sequence recognition. Its title captures a problem more focused than building a human mind: how a computational system can recognize structure in information that unfolds over time.${ref(6,8)}</p>
 <p>Bengio's ACM recollection describes an initially lonely research direction and the importance of finding people interested in neural networks, including Geoffrey Hinton and Yann LeCun, at conferences. The later grouping of their names can make their association seem preordained. In the recollection, it was also a discovery that the questions occupying him belonged to a wider scientific conversation.${ref(3)}</p>
 <p>Postdoctoral work took him to MIT and Bell Labs. He joined Université de Montréal in 1993. Quebec's institutional biography traces the laboratory he built there through LISA to Mila. The progression matters: a research institution is not created by a prize ceremony. It emerges from the repeated work of bringing people together around questions, keeping experiments running, training students, and making enough progress that another cohort can continue.${ref(4,7)}</p>
 <p>His education therefore supplied two kinds of apprenticeship: the technical discipline of studying a tractable problem, and the social discovery that difficult research needs a community. Both would become part of his contribution.</p>`],
 ["difficulty","A discovery about why learning fails",`
 <p>One important early paper did not announce an astonishing capability. It explained a difficulty. In 1994, Bengio, Patrice Simard, and Paolo Frasconi investigated why gradient-based training struggles to teach recurrent neural networks long-term dependencies. A system processing a sequence may need something encountered much earlier, yet the signals used to adjust its parameters can fail to preserve that relationship effectively.${ref(9)}</p>
 <p>To understand the practical problem, imagine a task in which the last instruction depends on a clue near the beginning. A learner must do more than react to the latest input. It must retain useful information and learn which earlier events matter. This is an explanatory example, not a description of an experiment in the paper. It illustrates why a computational technique can look promising and still encounter a deep obstacle.</p>
 <p>Such work is an essential counterweight to breakthrough stories. Diagnosing a limitation gives other researchers a clearer target. It can shape subsequent approaches without its authors supplying every eventual solution. Bengio's early record shows this less glamorous form of achievement: not simply making a network perform, but identifying why the obvious training procedure could be inadequate. Understanding failure was part of the science before safety became his public cause.</p>`],
 ["language","Giving words a learnable representation",`
 <p>In 2003, Bengio, Réjean Ducharme, Pascal Vincent, and Christian Jauvin published a neural probabilistic language model. Rather than treating every word sequence as an isolated item to count, their method learned numerical representations of words together with a model of sequence probabilities. Shared structure could help it generalize beyond combinations directly encountered in the training data. The paper compared results with established statistical language models on two text collections.${ref(10)}</p>
 <p>The distinction is easier to grasp through an analogy. A catalog can record every object it has seen, while a useful representation can place unfamiliar objects in relation to familiar ones. The model did not acquire human understanding merely because its representations were useful. It supplied a way of organizing information that made a difficult prediction problem more manageable.</p>
 <p>This is a recurring pattern in Bengio's work: ask what the machine should learn internally, not only which answer it should produce. The contribution belongs to the named team and to a larger history of language modeling. Present-day fluency should not be read backward into the 2003 system. Its importance lies in a concrete research step that others could inspect and extend, not in an anachronistic claim that a contemporary chatbot had already been invented.</p>`],
 ["persistence","Keeping a difficult research direction alive",`
 <p>Scientific persistence needs more than a stubborn individual. CIFAR's historical account describes the 2004 creation of its Neural Computation and Adaptive Perception program, which helped sustain a research community around ideas that were not yet the center of the technology industry. Hinton and fellow researchers had an institutional setting in which to exchange work across disciplinary boundaries.${ref(11)}</p>
 <p>By 2009, Hugo Larochelle, Bengio, Jérôme Louradour, and Pascal Lamblin were examining strategies for training deeper networks. Their study investigated layer-by-layer unsupervised pretraining and the conditions under which it helped, building on earlier work by Hinton and others. This was not a universal recipe that erased all training difficulties. It was a systematic effort to understand initialization, learning, and generalization in networks with multiple layers.${ref(12)}</p>
 <p>The contrast with the teenage computer story is useful. Writing a game offers relatively direct feedback: the program runs, fails, or behaves incorrectly. Research may require years of making the question sharper before the useful result becomes obvious. Funding, colleagues, and students make that interval survivable. Recognition that notices only the eventual winners misses the infrastructure that allowed uncertain work to continue at all.</p>`],
 ["attention","Translation, attention, and shared credit",`
 <p>Another obstacle was compression. Early neural translation systems could try to encode a whole source sentence into a fixed-length representation before generating a translation. Dzmitry Bahdanau, Kyunghyun Cho, and Bengio proposed allowing the model to attend to relevant parts of the source while producing each target word. Their preprint appeared in 2014 and was accepted at ICLR 2015. On English-to-French translation, the reported system reached performance comparable to a strong phrase-based approach.${ref(13)}</p>
 <p>The everyday analogy is a translator who can look back at the original instead of being required to work entirely from a single compressed recollection. That analogy should not be mistaken for a claim that the model thought like a translator. It helps explain the engineering advantage of revisiting relevant information.</p>
 <p>Attention became central to later architectures, but authorship must remain precise. The 2017 Transformer paper, <em>Attention Is All You Need</em>, was written by Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan Gomez, Łukasz Kaiser, and Illia Polosukhin. Bengio was not among its authors.${ref(14)}</p>
 <p>A biography can connect these developments without merging them into one person's achievement. Bahdanau and Cho deserve more than a passing footnote in an account of the earlier work. The story becomes more informative, not less impressive, when the chain of contributions remains visible.</p>`],
 ["generative-models","Learning through a contest",`
 <p>In the same period, a different team explored an unusual learning arrangement. Ian Goodfellow, Jean Pouget-Abadie, Mehdi Mirza, Bing Xu, David Warde-Farley, Sherjil Ozair, Aaron Courville, and Bengio introduced generative adversarial networks in 2014. One model generated samples; another learned to distinguish generated samples from training data. Their competing objectives supplied a training process for learning a data distribution.${ref(15)}</p>
 <p>The paper provided both a mathematical formulation and experimental evidence of the framework's potential. It did not establish that every training run would converge perfectly, or that plausible output was necessarily truthful. Nor should all later generative AI be described as a GAN. Different methods can produce superficially similar outputs while relying on different training mechanisms.</p>
 <p>For a life story, the important point is the variety of roles within a productive laboratory. A senior researcher's name can appear on work whose central development is associated with a younger colleague. Goodfellow's lead authorship and the full team's participation belong at the center of this chapter. Bengio's contribution includes helping sustain a setting in which such work could be pursued; it does not entitle him to absorb the identities of the people around him.</p>`],
 ["tools-and-teaching","The work that makes other work possible",`
 <p>Not all contributions arrive as a new model. The Theano Development Team's 2016 paper describes software for defining, optimizing, and evaluating mathematical expressions efficiently, including on graphics processors. Contributors included Frédéric Bastien, James Bergstra, Olivier Breuleux, Pascal Lamblin, Bengio, and a much larger team. The collective author designation is a reminder that usable research infrastructure depends on sustained engineering as well as ideas.${ref(16)}</p>
 <p>A framework can save researchers from rebuilding the same machinery before every experiment. Its value is practical: more time can go into the question being investigated. That does not make every experiment conducted with it successful. It makes experimentation more accessible and repeatable. Here, the object of recognition is enabling work, not a claim that software alone delivered a particular medical or social outcome.</p>
 <p>Teaching provided another route. Goodfellow, Bengio, and Courville's 2016 textbook <em>Deep Learning</em> organized mathematical foundations, established methods, and research directions into an extended course of study. An authorized online edition is available for reading. RACH has not measured how many careers it changed, but the educational resource itself is verifiable.${ref(17)}</p>
 <p>These contributions broaden the meaning of a scientific life. A researcher can matter through the tools people inherit and the explanations that let them enter a field, not only through the experiments bearing their name.</p>`],
 ["montreal","Building a place where researchers could stay",`
 <p>Montreal was not merely the address on Bengio's papers. In his 2025 public-service interview, he recalled wanting advances in his field to support a Canadian research ecosystem as industrial interest grew. The choice to remain connected to an academic community is part of the public account he gives of his career.${ref(5)}</p>
 <p>Daniel McCabe's 2018 reporting for McGill News makes that community more visible. It describes contributions from researchers including Joëlle Pineau, Doina Precup, and Jackie Chi Kit Cheung, along with collaboration across Montreal institutions. The article records Bengio's appreciation for the mathematical education he received at McGill. These are historical descriptions, not an assertion that everyone still holds the same position today.${ref(18)}</p>
 <p>In 2019, McGill announced that Bengio shared the 2018 A.M. Turing Award with Hinton and LeCun. The distinction recognized deep-learning contributions, but even a shared prize cannot represent every person whose work made a field possible. Students, research staff, software maintainers, and public institutions remain outside the familiar three-name shorthand.${ref(6)}</p>
 <p>RACH's interpretation is that institution-building should be judged alongside publication. A place where people can train, challenge one another, and continue a line of inquiry is a durable contribution. It is also a collective one, supported by people who may never become the subject of a major profile.</p>`],
 ["element-ai","The commercial chapter was not a simple triumph",`
 <p>Bengio was also a co-founder of Element AI, established in 2016. ServiceNow's acquisition announcement identifies a broader founding group including Jean-François Gagné, Anne Martel, Nicolas Chapados, Jean-Sébastien Cournoyer, and Philippe Beaudoin. The acquisition was announced in November 2020 and, according to the release's update, completed on January 8, 2021. ServiceNow presented the transaction as an investment in AI capabilities and a Canadian innovation hub.${ref(19)}</p>
 <p>Independent reporting recorded a less celebratory dimension. Francis Halin reported in Le Journal de Montréal that a collective-layoff notice covered 42 employees; a Quebec labour-ministry spokesperson confirmed the notice. The article also carried ServiceNow's commitment to support a smooth transition for people not retained. That reporting concerns the transaction and its employees, not an established allegation of personal misconduct by Bengio.${ref(20)}</p>
 <p>The episode resists a biography's temptation to turn every institutional move into progress. Scientific distinction does not guarantee that a company will succeed independently, or that a sale will benefit everyone who helped build it. Employees experience a corporate outcome differently from founders, investors, or acquiring executives. Their presence belongs in the story even when the available record does not allow an exhaustive judgment about the business.</p>`],
 ["responsibility","Responsibility before the recent safety turn",`
 <p>Bengio's concern about AI's consequences did not begin with LawZero. The Montréal Declaration for the Responsible Development of Artificial Intelligence, presented in December 2018, set out principles concerning well-being, autonomy, privacy, democratic participation, equity, and related responsibilities. Its development involved a wider deliberative effort, not a scientist issuing rules for everyone else.${ref(21,22)}</p>
 <p>Marc-Antoine Dilhac, Christophe Abrassart, Catherine Régis, and other contributors helped shape the intellectual and institutional work behind that initiative. Citizen participation matters to its meaning. Questions about acceptable technology cannot be answered solely by the people technically equipped to build it. A declaration is nevertheless a statement of principles, not proof that the systems associated with its supporters comply with them.${ref(21)}</p>
 <p>That distinction clarifies the challenge of moving from ethics to practice. Respecting autonomy must mean something in a concrete deployment; privacy must survive the actual handling of data; democratic participation requires more than inviting people to applaud a finished product. These are RACH's editorial observations about the principles, not claims that the declaration solved those problems. Bengio's participation demonstrates an engagement with responsibility that predates his more recent emphasis on potentially catastrophic risks.</p>`],
 ["changing-mind","The scientist who revised his sense of urgency",`
 <p>In the 2018 McGill News account, Bengio treated human-level AI as distant and rejected dramatic machine-rebellion scenarios as a sound description of the science then available. That dated position is worth preserving. Public figures should not be made retrospectively consistent by removing the views they later reconsidered.${ref(18)}</p>
 <p>In a 2026 Radio Davos interview with Robin Pomeroy, Bengio described a shift after using ChatGPT following its late-2022 release. He connected the change not only to technical concerns about controlling learned behavior, but to thinking about the future facing his children and grandchild. This is his public explanation of his motivation. RACH did not independently witness the realization and does not need to identify family members to explain its relevance.${ref(23)}</p>
 <p>A change of mind is neither automatic evidence of wisdom nor a reason to dismiss the person. What matters is whether the revised position can be examined. Bengio's later work puts questions about training objectives, predictions, and dangerous behavior into a form other researchers can contest. His authority comes from relevant expertise, but expertise does not turn a forecast into a fact. The interesting biographical tension is that the researcher who helped make learning systems more capable now argues that capability alone is an insufficient measure of progress.</p>`],
 ["risk-and-disagreement","Whose risks count?",`
 <p>AI criticism has never consisted of a single argument. In their 2021 paper on large language models, Emily M. Bender, Timnit Gebru, Angelina McMillan-Major, and Shmargaret Shmitchell examined environmental and financial costs, dataset curation, and the dangers of treating scale as an adequate research objective. Their work supplies a critical perspective on harms and incentives that cannot be reduced to speculation about future superintelligence.${ref(24)}</p>
 <p>This is not presented as their response to Bengio's 2026 research. It establishes why a recognition profile should ask what a safety agenda includes and leaves out. An intervention aimed at future loss of control does not automatically address discrimination, privacy, working conditions, or the distribution of power. Those questions require their own evidence and affected communities' participation.</p>
 <p>The International AI Safety Report that Bengio chairs is itself a collective project, with more than 100 independent experts contributing to its 2026 edition. Its executive summary distinguishes malicious use, malfunction, and systemic risks. In its February assessment, it said current systems lacked the capabilities needed for the strongest irreversible-loss-of-control scenarios while noting progress in relevant capabilities and substantial uncertainty. It also emphasized limitations in evaluating how systems will behave outside tests.${ref(25,26)}</p>
 <p>That dated assessment is more useful than treating either reassurance or catastrophe as settled. Bengio's personal warnings and a multi-author evidence review are related activities, but they are not interchangeable statements.</p>`],
 ["lawzero","Starting again, with a different objective",`
 <p>In June 2025, Bengio announced LawZero, a nonprofit intended to prioritize safety over commercial imperatives. The institutional choice gives his change of emphasis a practical form: a team, a research program, and an attempt to organize incentives differently. The announcement establishes the intention. It does not establish that nonprofit status makes a research organization free from conflicts or guarantees successful outcomes.${ref(27)}</p>
 <p>Its current leadership includes Sam Ramadori as co-president and executive director, with Bengio responsible for scientific direction; Joumana Ghosn is senior director of research. Maria Eitel chairs its board. Naming these colleagues prevents a new institution from being mistaken for a one-person project. Research, operations, governance, and engineering all influence what an organization can actually deliver.${ref(28)}</p>
 <p>LawZero also announced a donation of computing resources from NVIDIA in July 2026. The announcement illustrates that an organization seeking a different development model still needs material infrastructure. RACH treats the donation as a reported resource contribution, not independent validation of its scientific claims.${ref(29)}</p>
 <p>The tension is productive to examine rather than explain away. Alternative institutions have to acquire resources while protecting their stated purpose. Whether LawZero succeeds will depend on inspectable research and accountable decisions, not solely on its founder's reputation or the category under which it is incorporated.</p>`],
 ["working-on-now","What they are working on now — September 22, 2026",`
 <p>The current program centers on Scientist AI. A June 28 preprint, revised July 10, sets out a formal safety argument for a predictor that estimates what is true without selecting answers to bring about goals of its own. Bengio's coauthors include Oliver Richardson, Tomáš Gavenčiak, Michael Cohen, Damiano Fornasiere, Gael Gendron, Iulian Serban, Joumana Ghosn, and others. The proposal separates statements about people's goals from goals the predictor itself would adopt.${ref(30)}</p>
 <p>The argument depends on assumptions about training and the rarity of dangerous predictors. It does not demonstrate that a deployed system is safe in every real-world setting, and the authors explicitly allow that the predictor could be incorporated into an agentic system. It is a research contribution to test, not a completed safety guarantee.${ref(30)}</p>
 <p>On September 11, Bengio published an essay exploring how imitation, reinforcement learning, and imperfect reward signals might explain unwanted agent behavior. He explicitly treats language about systems trying or seeking as a shorthand for mechanisms, not evidence of consciousness. The essay advances hypotheses and concerns about future developments; those are not independently established forecasts.${ref(31)}</p>
 <p>On September 16, Canada and Germany announced plans to invest CAD 150 million and EUR 100 million respectively in LawZero. The Canadian release says German funding is subject to European Commission notification. These are funding plans, not verified disbursements or proof of efficacy. They make the present chapter consequential by potentially expanding the resources available to test the approach.${ref(32)}</p>
 <p>Official profiles, research listings, the new paper, and public interview records were checked for this article. Authentic X and LinkedIn links were identified through Mila, but their feeds could not be read. The current-work account therefore rests on accessible records, not presumed social-media updates.${ref(1,2,34)}</p>`],
 ["recognition","Why RACH recognizes Yoshua Bengio",`
 <p>RACH recognizes Bengio for research contributions to learning representations, neural language modeling, attention-based translation, and generative models; for shared tools and teaching; and for helping build a research community that other people could join. The papers, software record, textbook, and institutions provide concrete grounds for that judgment. Recognition is not a claim that every application of deep learning benefits humanity.</p>
 <p>His public reconsideration of AI's direction adds an important human dimension. A researcher can spend decades pursuing a capability and still ask whether the way it is being developed should change. That willingness deserves examination, not unquestioning agreement. LawZero's ambitions must face the same standards of evidence as the systems it seeks to improve. Funding, prestigious supporters, and a famous scientific founder cannot substitute for demonstrated safety.</p>
 <p>The teenage programmer, the investigator of training failures, the collaborator, the institution-builder, and the safety advocate are parts of one unfinished life. Its lesson is not that persistence always proves a dissenter right. It is that meaningful work requires both commitment and revision: enough commitment to investigate difficult questions, and enough openness to reconsider what success should mean. The next chapter belongs to the evidence Bengio and his colleagues produce—and to the people affected by the technology they help shape.</p>`]
];
const narrative=sections.map(([id,title,html])=>`<section id="${id}"><h2>${title}</h2>${html}</section>`).join("\n");
const wordCount=narrative.replace(/<sup[\s\S]*?<\/sup>/g,"").replace(/<[^>]+>/g," ").trim().split(/\s+/).length;
const imageSource=sources[32].url;
const imageDisplayNote="Original file; cropped and slightly desaturated for display by RACH. Display adaptation licensed CC BY-SA 4.0.";
const body=`<article class="profile-article">
 <header class="profile-intro"><figure class="profile-portrait"><img src="/assets/profiles/yoshua-bengio-xuthoria.jpg" alt="Yoshua Bengio wearing a black shirt and conference lanyard at ICLR 2025" width="3648" height="5472" style="height:auto"><figcaption>Yoshua Bengio at ICLR, Singapore, April 28, 2025. Photo: <a href="${imageSource}" target="_blank" rel="noreferrer">Xuthoria / Wikimedia Commons</a> — <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="license noreferrer">CC BY-SA 4.0</a>. ${imageDisplayNote} No endorsement by the photographer or subject is implied.${ref(33)}</figcaption></figure>
 <div class="profile-intro-copy"><p class="profile-series-label">RACH Profiles · Artificial Intelligence</p><p class="profile-deck">Yoshua Bengio: Helping Machines Learn—and Rethinking What Comes Next</p><p>From two brothers programming home computers to neural-network breakthroughs, Montreal's research community, and a new effort to make AI safer.</p><div class="profile-byline"><span>RACH · AI-assisted public-record biography</span><span>Published September 22, 2026</span><span>Reported through September 22, 2026</span><span>${wordCount.toLocaleString("en-US")} narrative words</span></div><dl class="profile-facts"><div><dt>Current roles</dt><dd>Full Professor, Université de Montréal; Co-President and Scientific Director, LawZero; Founder and Scientific Advisor, Mila.${ref(1,2,28)}</dd></div><div><dt>Research focus</dt><dd>Learning representations, neural networks, and AI safety.</dd></div><div><dt>Evidence boundary</dt><dd>Foundational research is demonstrated work. A proposed safe-by-design AI remains a research objective.</dd></div></dl></div></header>
 <div class="profile-content-grid"><nav class="profile-toc" aria-label="In this profile"><p class="eyebrow">In this profile</p>${sections.map(([id,title])=>`<a href="#${id}">${title}</a>`).join("")}<a href="#methodology">Methodology and corrections</a><a href="#sources-heading">Sources</a></nav><div class="profile-copy">${narrative}
 <section id="methodology" class="profile-methodology"><h2>Methodology, disclosure, and corrections</h2><p>This independent public-record biography was researched, drafted, and internally checked with AI assistance for RACH. Publication is under standing authorization from RACH's owner; it is not based on a new subject interview or a claimed human scientific review. RACH did not contact Bengio, his collaborators, critics, or representatives. Recollections and institutional claims are attributed; explanatory analogies and editorial judgments are not reported events.</p><p>Current official profiles, institutional and company pages, research records, and public interview listings were checked September 22, 2026. The ACM interview transcript was retrieved during preliminary reporting; publication-day access was restricted. The Radio Davos page labels its transcript machine-generated, so no verbatim quotations from it are used. X and LinkedIn feeds were inaccessible. The 2026 safety preprint is not described as peer-reviewed validation; the February safety report is a dated assessment, not a September certification.</p><p>Recognition is an editorial judgment, not a formal scientific award, implied partnership, or endorsement of any company or product. No sponsorship, payment, or endorsement was arranged with the subject in preparing this article. Internal strategic considerations do not determine the public recognition rationale.</p><p>Send documented corrections to <a href="mailto:info@rachorg.org?subject=Yoshua%20Bengio%20profile%20correction">info@rachorg.org</a>. Material updates will be dated. Narrative word count excludes the byline, navigation, methodology, and source list.</p></section>
 <section class="profile-sources" aria-labelledby="sources-heading"><h2 id="sources-heading">Sources</h2><ol>${sources.map(s=>`<li id="source-${s.id}"><a href="${s.url}" target="_blank" rel="noreferrer"><cite>${s.title}</cite></a>, ${s.publisher}. ${s.note}</li>`).join("\n")}</ol></section></div></div></article>`;
export const yoshuaBengio={
 path:"/profiles/yoshua-bengio",slug:"yoshua-bengio",type:"profile",draft:false,title:"Yoshua Bengio",heading:"Yoshua Bengio",
 seoTitle:"Yoshua Bengio: Helping Machines Learn—and Rethinking What Comes Next | RACH Profiles",eyebrow:"RACH Profiles · The People Building What Comes Next",
 description:"Yoshua Bengio's life from early programming to deep learning, Montreal institution-building, collaborators, setbacks, and LawZero's current AI safety research.",
 image:"/assets/profiles/yoshua-bengio-xuthoria.jpg",imageAlt:"Yoshua Bengio wearing a black shirt and conference lanyard at ICLR 2025",imageWidth:3648,imageHeight:5472,
 imageCredit:"Xuthoria / Wikimedia Commons, CC BY-SA 4.0",imageCreator:"Xuthoria",imageCreatorAccount:"Xuthoria",imageSource,
 imageSourceRevision:"https://commons.wikimedia.org/w/index.php?title=File:ICLR_2025_-_Yoshua_Bengio_03.jpg&oldid=1085362260",imageLicense:"CC BY-SA 4.0",imageLicenseUrl:"https://creativecommons.org/licenses/by-sa/4.0/",imageCreditText:`Xuthoria / Wikimedia Commons — CC BY-SA 4.0. ${imageDisplayNote}`,imageDisplayNote,imageCaption:`Yoshua Bengio, ICLR, Singapore, April 28, 2025. Xuthoria / Wikimedia Commons, CC BY-SA 4.0. ${imageDisplayNote}`,
 category:"Artificial Intelligence",secondaryCategories:[],deck:"From two brothers programming home computers to neural-network breakthroughs, Montreal's research community, and a new effort to make AI safer.",
 recognitionSummary:"For shared advances in learning representations, neural language modeling, attention and generative models, and for research tools, teaching, and institution-building—not for a proven guarantee of safe AI.",
 author:"RACH — AI-assisted editorial",datePublished:"2026-09-22",dateModified:"2026-09-22",reportingCutoff:"2026-09-22",wordCount,body,
 about:{name:"Yoshua Bengio",jobTitle:["Full Professor, Université de Montréal","Co-President and Scientific Director, LawZero","Founder and Scientific Advisor, Mila"],sameAs:[sources[0].url,sources[1].url]},sources
};
